name: Sync branches with main

on:
  push:
    branches:
      - main  # This workflow runs when a push is made to 'main'

jobs:
  rebase:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          
      - name: Fetch all branches
        run: |
          git fetch --all

      - name: Rebase develop onto main
        run: |
          git checkout develop
          git pull origin main --rebase
          git push origin develop --force-with-lease  # If necessary, force push

      - name: Rebase feature branches onto main
        run: |
          for branch in develop feature/deployment-and-apk feature/device-sensors-and-location feature/firebase-authentication feature/local-database-sqlite feature/mvp-data-connection feature/mvp-ui-navigation feature/project-setup-and-structure feature/ui-animations-and-charts; do
            git checkout $branch
            git pull origin main --rebase
            git push origin $branch --force-with-lease  # Force push to update the remote branch
          done
