name: Sync all branches with main

on:
  push:
    branches:
      - main  # This workflow runs when a push is made to 'main'

jobs:
  sync-branches:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Required for full rebase operations

      - name: Set up Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Fetch all branches
        run: |
          git fetch --all

      - name: Sync branches with main
        run: |
          branches=("develop" "feature/deployment-and-apk" "feature/device-sensors-and-location" "feature/firebase-authentication" "feature/local-database-sqlite" "feature/mvp-data-connection" "feature/mvp-ui-navigation" "feature/project-setup-and-structure" "feature/ui-animations-and-charts")

          for branch in "${branches[@]}"; do
            echo "Rebasing $branch onto main..."
            git checkout $branch || git checkout -b $branch origin/$branch
            git rebase origin/main || {
              echo "Conflict detected in $branch, resolving in favor of main..."
              git checkout --theirs .
              git add .
              git rebase --continue
            }
            git push origin $branch --force-with-lease
          done
