name: Sync all branches with main

on:
  push:
    branches:
      - main  # This workflow runs when a push is made to 'main'

permissions:
  contents: write  # Needed for pushing changes

jobs:
  sync-branches:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Required for full history (rebase and merge)

      - name: Set up Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Authenticate using PAT
        run: |
          git remote set-url origin https://x-access-token:${{ secrets.GH_PAT }}@github.com/Paulidex/EAN-Elections.git

      - name: Fetch all branches
        run: |
          git fetch --all

      - name: Sync branches with main
        run: |
          branches=("develop" "feature/deployment-and-apk" "feature/device-sensors-and-location" "feature/firebase-authentication" "feature/local-database-sqlite" "feature/mvp-data-connection" "feature/mvp-ui-navigation" "feature/project-setup-and-structure" "feature/ui-animations-and-charts")

          for branch in "${branches[@]}"; do
            echo "Processing branch: $branch"
            git checkout $branch || git checkout -b $branch origin/$branch
            git merge origin/main --no-edit || {
              echo "Merge conflict detected in $branch, resolving in favor of main..."
              git checkout --theirs .
              git add .
              git commit -m "Auto-merge main into $branch with conflict resolution in favor of main"
            }

            if [[ "$branch" == "develop" ]]; then
              echo "Protected branch detected, using normal push..."
              git push origin $branch
            else
              echo "Feature branch detected, pushing with force-with-lease..."
              git push origin $branch --force-with-lease
            fi
          done
