name: Sync forked branches with main

on:
  push:
    branches:
      - main  # Triggers when they click "Fetch upstream" and update their main branch

  workflow_dispatch:  # Optional: allows manual execution from GitHub Actions tab

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Fetch and merge main into all branches
        run: |
          git fetch origin

          branches=("develop" "feature/deployment-and-apk" "feature/device-sensors-and-location" "feature/firebase-authentication" "feature/local-database-sqlite" "feature/mvp-data-connection" "feature/mvp-ui-navigation" "feature/project-setup-and-structure" "feature/ui-animations-and-charts")

          for branch in "${branches[@]}"; do
            echo "Updating $branch with main..."
            git checkout $branch || git checkout -b $branch origin/$branch
            git merge origin/main --no-edit || {
              echo "Conflict in $branch. Resolving in favor of main..."
              git checkout --theirs .
              git add .
              git commit -m "Auto-merge main into $branch"
            }
            git push origin $branch
          done
