name: Sync branches with main

on:
  push:
    branches:
      - main  # This workflow runs when a push is made to 'main'

jobs:
  rebase:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Necesario para operaciones de rebase completas

      - name: Set up Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Fetch all branches
        run: |
          git fetch --all

      - name: Rebase develop onto main with auto conflict resolution
        run: |
          git checkout develop
          git rebase origin/main || {
            echo "Conflicto detectado, resolviendo con contenido de main..."
            git checkout --theirs .
            git add .
            git rebase --continue
          }
          git push origin develop --force-with-lease

      - name: Rebase feature branches onto main with auto conflict resolution
        run: |
          for branch in feature/deployment-and-apk feature/device-sensors-and-location feature/firebase-authentication feature/local-database-sqlite feature/mvp-data-connection feature/mvp-ui-navigation feature/project-setup-and-structure feature/ui-animations-and-charts; do
            git checkout $branch
            git rebase origin/main || {
              echo "Conflicto en $branch, resolviendo con contenido de main..."
              git checkout --theirs .
              git add .
              git rebase --continue
            }
            git push origin $branch --force-with-lease
          done
